### PR TITLE
Escape stubgen names

### LINKED ISSUE #392: Not valid rust error from stubgen
Running stubgen on [this schema](https://gist.github.com/u9g/b558a6a575d0a2b0f1cdd8ed7e8b3b83) throws: 
```
thread 'main' panicked at 'not valid Rust: Error("expected expression")', /home/u9g/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trustfall_stubgen-0.2.0/src/root.rs:130:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by u9g**
Resolves #392.

### CODE REVIEW

File: trustfall_stubgen/src/util.rs [hunk 1]
```diff
@@ -138,3 +138,11 @@ pub(crate) fn field_value_to_rust_type(
         #base.#suffix
     }
 }
+
+pub fn escaped_rust_name(name: String) -> String {
+    if name == "type" {
```
Comment (u9g) [inline trustfall_stubgen/src/util.rs:143]: I only escape type, what other keywords should we escape?

File: trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+  """
+  Name of the transformation operation to perform.
+  """
+  op: String!
+) on FIELD
+
+"""
+All the possible data types where querying can begin in this API.
+"""
+type RootSchemaQuery {
```
Comment (u9g) [inline trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql:45]: Are there any cases I missed?

**Review by u9g — COMMENTED** [review]
Some thoughts

File: trustfall_stubgen/src/util.rs (hunk 1 above)
Comment (obi1kenobi) [reply trustfall_stubgen/src/util.rs:143]: any keyword mentioned anywhere on this page (strict, weak, or reserved): https://doc.rust-lang.org/reference/keywords.html

File: trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql (hunk 2 above)
Comment (obi1kenobi) [reply trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql:45]: probably good to add a few more test cases using keywords from here: https://doc.rust-lang.org/reference/keywords.html

File: trustfall_stubgen/src/util.rs [hunk 3]
```diff
@@ -138,3 +138,11 @@ pub(crate) fn field_value_to_rust_type(
         #base.#suffix
     }
 }
+
+pub fn escaped_rust_name(name: String) -> String {
```
Comment (obi1kenobi) [inline trustfall_stubgen/src/util.rs:142]: The result of this function is always used by reference, so let's make this take `&str` and have it return `Cow<'_, str>` to avoid some unnecessary cloning:
https://doc.rust-lang.org/std/borrow/enum.Cow.html

**Review by obi1kenobi — COMMENTED** [review]
Nice job! There's a small-but-tricky design question that needs to be resolved first, and otherwise this is good to go.

File: trustfall_stubgen/src/util.rs (hunk 1 above)
Comment (u9g) [reply trustfall_stubgen/src/util.rs]: [061c32e](https://github.com/obi1kenobi/trustfall/pull/406/commits/061c32e308a1b6d5b5330524c3387bb8ac195955)

File: trustfall_stubgen/src/util.rs [hunk 4]
```diff
@@ -138,3 +138,11 @@ pub(crate) fn field_value_to_rust_type(
...
+    if name == "type" {
+        name + "_"
```
[the remark this answers is not in the document]
Comment (u9g) [reply trustfall_stubgen/src/util.rs]: We decided on simply outlawing any schema that uses the name `Type` and `Type_` and just throw an error, that was implemented in [25f2dee](https://github.com/obi1kenobi/trustfall/pull/406/commits/25f2dee40af223e6d87defd703b82f423149949e)

File: trustfall_stubgen/src/util.rs (hunk 3 above)
Comment (u9g) [reply trustfall_stubgen/src/util.rs:142]: It's no longer only used by reference, see: [25f2dee](https://github.com/obi1kenobi/trustfall/pull/406/commits/25f2dee40af223e6d87defd703b82f423149949e) that stores the String's by value in the map, so it's much easier to keep the String return type

File: trustfall_stubgen/src/edges_creator.rs [hunk 5]
```diff
@@ -4,6 +4,8 @@ use maplit::btreemap;
 use quote::quote;
 use trustfall::{Schema, SchemaAdapter, TryIntoStruct};
 
+use crate::util::escaped_rust_name;
```
Comment (obi1kenobi) [inline trustfall_stubgen/src/edges_creator.rs:7]: can you get this from `super::util::` below?

File: trustfall_stubgen/src/root.rs [hunk 6]
```diff
@@ -400,3 +403,100 @@ fn make_vertex_file(
...
+        if let Some(v) = v {
+            panic!(
+                "cannot generate adapter for a schema containing both '{}' and '{}' vertices, consider renaming one of them",
+                v, &row.name
+            );
+        }
+    }
+}
+
+fn ensure_no_edge_name_keyword_conflicts(
```
Comment (obi1kenobi) [inline trustfall_stubgen/src/root.rs:445]: This function can probably use a better name, more in line with the panic message below

File: trustfall_stubgen/src/root.rs [hunk 7]
```diff
@@ -400,3 +403,100 @@ fn make_vertex_file(
...
+            let property_name_for_map = property_name.clone();
+            let converted = escaped_rust_name(to_lower_snake_case(&property_name_for_map));
+            let v = uniq.insert(converted, property_name_for_map);
+            if let Some(v) = v {
+                panic!(
+                    "cannot generate adapter for a schema containing both '{}' and '{}' as field names on vertex '{}', consider renaming one of them",
+                    v, &property_name, &row.name
+                );
+            }
+        }
```
Comment (obi1kenobi) [inline trustfall_stubgen/src/root.rs:500]: rather than having the same loop twice in a row over two different iterables, zip the iterators together then write the loop once
```suggestion
        for field_name in row.edge_names.iter().chain(row.property_names.iter()) {
            let converted = escaped_rust_name(to_lower_snake_case(field_name));
            if let Some(v) = uniq.insert(converted, field_name.clone()); {
                panic!(
                    "cannot generate adapter for a schema containing both '{}' and '{}' as field names on vertex '{}', consider renaming one of them",
                    v, &field_name, &row.name
                );
            }
        }
```

File: trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql (hunk 2 above)
Comment (obi1kenobi) [reply trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql:45]: Still probably good to throw in a few more reserved keywords here.

**Review by obi1kenobi — COMMENTED** [review]
Broadly looks good, just a few small things to polish up.

File: trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql (hunk 2 above)
Comment (u9g) [reply trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/schema.graphql:45]: [fa63cb8](https://github.com/obi1kenobi/trustfall/pull/406/commits/fa63cb817ffdc9e6638b4a85ccea6e25588408a9)

File: trustfall_stubgen/src/edges_creator.rs (hunk 5 above)
Comment (u9g) [reply trustfall_stubgen/src/edges_creator.rs]: [19db2ef](https://github.com/obi1kenobi/trustfall/pull/406/commits/19db2ef0228d3aecf9d8d78dcdb5d4220a1a6f3f)

File: trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/vertex.rs [hunk 8]
```diff
@@ -1,6 +1,9 @@
...
 #[derive(Debug, Clone, trustfall::provider::TrustfallEnumVertex)]
 pub enum Vertex {
-    Type(()),
-    Type2(()),
+    unsafe2(()),
+
+    use_(()),
+
+    use2(()),
 }
```
[the remark this answers is not in the document]
Comment (u9g) [reply trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/vertex.rs]: [aae96cf](https://github.com/obi1kenobi/trustfall/pull/406/commits/aae96cfd8a46cf90562ea619dc583f6fecb2c1db)

[the remark this answers is not in the document]
Comment (u9g) [reply trustfall_stubgen/test_data/expected_outputs/use_reserved_rust_names_in_schema/adapter/vertex.rs]: especially this comment: https://github.com/obi1kenobi/trustfall/pull/406/commits/aae96cfd8a46cf90562ea619dc583f6fecb2c1db#diff-78e3b031bbc47a6bd07fe535e64778cc8f9030a9b983f9ebe8ef4d16ad61f581R432-R433

File: trustfall_stubgen/src/root.rs (hunk 7 above)
Comment (u9g) [reply trustfall_stubgen/src/root.rs]: Done!

File: trustfall_stubgen/src/util.rs [hunk 9]
```diff
@@ -17,6 +17,14 @@ pub(crate) fn to_lower_snake_case(value: &str) -> String {
     result
 }
 
+pub(crate) fn upper_case_variant_name(value: &str) -> String {
+    let mut chars = value.chars();
+    let first_char = chars.next().unwrap().to_ascii_uppercase();
```
Comment (obi1kenobi) [inline trustfall_stubgen/src/util.rs:22]:
```suggestion
    let first_char = chars.next().expect("unexpectedly got an empty string").to_ascii_uppercase();
```

**Review by obi1kenobi — APPROVED** [review]
